# === Loading === #
loading:
    min: 0
    max: 1.001
    steps: 10

#  === Geometry === #
geometry:
    geometric_dimension: 2
    geom_type: "bar"
    Lx: 1.
    Ly: .1
    mesh_size: 0.05
    mesh_size_factor: 3

#  === Material === #
model:
    E: 1.
    D: 1.
    sigma_D0: 1.
    nu: 0.15
    model_dimension: 2
    model_type: "2D"
    # could be "2D"/ "3D" / "plane_stress" / "plane_strain"
    order: 2
    alpha_penalty: 100.
# === Solver === #
solvers:
    elasticity:
        prefix: elasticity
        snes:
            snes_type: ksponly
            snes_stol: 1e-8
            snes_atol: 1e-8
            snes_rtol: 1e-8
            snes_max_it: 200
            # snes_divergence_tolerance: -1.0
            snes_monitor: ""
            ksp_type: preonly
            pc_type: lu
            pc_factor_mat_solver_type: mumps

    newton:
        snes_type: "vinewtonrsls"
        snes_linesearch_type: "basic"
        snes_rtol: 1.0e-8
        snes_atol: 1.0e-8
        snes_max_it: 30
        snes_monitor: ""
        linesearch_damping: 0.5

stability:
    order: 3
    maxmodes: 10
    checkstability: "True"
    continuation: "False"
    cont_rtol: 1.0e-10
    inactiveset_gatol: 1.e-6
    inactiveset_pwtol: 1.e-6
    is_elastic_tol: 1.e-6

    inertia:
        # MUMPS
        ksp_type: "preonly"
        pc_type: "cholesky"
        pc_factor_mat_solver_type: "mumps"
        mat_mumps_icntl_24: 1
        mat_mumps_icntl_13: 1

    eigen:
        eps_type: "krylovschur"
        # eps_type: "lanczos"
        # eps_monitor: ""
        eps_tol: 1.e-5
        eig_rtol: 1.e-8
        eps_max_it: 100
